config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_one_attached :photo
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @list = List.find(params[:id])
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Create your bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back home', lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2970&q=80https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2970&q=80https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2970&q=80')">
  <h1>Save any kind of movies</h1>
</div>

<div class="container ">

  <div class="d-flex flex-row-reverse">
    <%= link_to '+ Create a new list of movies', new_list_path, class:'btn btn-primary rounded-3 mt-2' %>
  </div>

  <ul class='list-inline d-flex justify-center'>
    <% @lists.each do |list| %>
      <li class="col-3 p-3 m-3 border border-grey rounded-4 text-center"><%= link_to list.name, list_path(list), class: 'text-decoration-none' %></li>
    <% end %>
  </ul>

</div>

app/views/lists/new.html.erb
<h1>Create your list of movies</h1>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back home', lists_path %>

app/views/lists/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
  <h1> <%= @list.name %> </h1>
</div>

<%= link_to 'Back home', lists_path %>


<%# <%= @list.photo.attached? ? cl_image_tag(@list.photo.key, height: 300, width: 400, crop: :fill) : image_tag("https://upload.wikimedia.org/wikipedia/fr/2/25/Logo_de_Top-Chef.png")%>

<div class="container ">

  <div class="d-flex flex-row-reverse">
    <%= link_to "Add a bookmark", new_list_bookmark_path(@list), class:'btn btn-primary rounded-3' %>
  </div>

  <div class="row d-flex justify-content-between my-4">
    <% @list.bookmarks.each do |bookmark|%>
      <div class="col-5 p-3 m-3 border border-grey rounded-4">
        <div class="d-flex">
          <p class="mb-0 fw-bold"><%= bookmark.movie.title%></p>
          <p class="mb-0 mx-2">•</p>
          <p class="mb-0 text-secondary"><%= bookmark.movie.rating %></p>
          <i class="mt-1 text-warning mx-1 fa-solid fa-star fs-6"></i>
        </div>
        <p class="lh-1 fs-6 fst-italic text-secondary"><%= bookmark.movie.overview %></p>
        <div class="d-flex mb-1">
          <i class="p-2 fa-solid fa-quote-left"></i>
          <div class="p-2"><%= bookmark.comment%></div>
          <div class="ms-auto p-2"><%= link_to 'Delete', bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'text-decoration-none text-danger' %></div>
        </div>
      </div>
    <% end %>
  </div>

</div>